### ISSUE TITLE
Change CLFLUSHOPT to CLFLUSH if CLFLUSHOPT is not supported

### ISSUE THREAD

**Issue by vijay03** [utsaslab/SplitFS#1]
SplitFS uses CLFLUSHOPT currently.

Check if the machine on which SplitFS is compiled supports CLFLUSHOPT (https://hjlebbink.github.io/x86doc/html/CLFLUSHOPT.html) and if not, use CLFLUSH instead.

**Comment by iabestever** [comment]
Hi Dr. Chidambaram, I would like to tackle this issue

**Comment by vijay03** [comment]
Thanks Ishank, please send us a PR with comments and an edit to README that explains how SplitFS would behave if CLFUSHOPT is not supported.

**Comment by vijay03** [comment]
Solved by #10
