### ISSUE TITLE
Details on git and tar microbenchmark

### ISSUE THREAD

**Issue by vschiavoni** [utsaslab/SplitFS#20]
Hello,
Would it be possible to release the  details of the git and tar measurements (Fig 6, c/f/i  in the sosp'19 paper)? 
What input file(s) and commands are executed for those workloads?
Thanks !

**Comment by rohankadekodi** [comment]
Hello,

For the "tar" workload, we use the command "tar -xf <tar_workload.tar.gz>". Here tar_workload.tar.gz contains the Linux kernel 4.18.10 source along with backup files of the "rsync" workload. 

For the "git" workload, we use the command "git add <git_workload>; git commit <git_workload>". Here git_workload is basically 10 copies of the Linux kernel 4.18.10. 

The workload details are mentioned in the [paper](https://www.cs.utexas.edu/~vijay/papers/sosp19-splitfs.pdf) in section 5.2 under "Utilities". 

I will add the binaries and the scripts for the tar and the git workload to the repository, soon. I will keep this issue open for now, and close it once I add the scripts and binaries. 

Thanks!
