### ISSUE TITLE
Port the POSIX test suite to SplitFS

### ISSUE THREAD

**Issue by vijay03** [utsaslab/SplitFS#4]
This requires ensuring that SplitFS correctly handles all the system calls made by the application. 

Would be useful to run the [POSIX test suite](https://www.tuxera.com/community/posix-test-suite/) on SplitFS.

Another candidate application is [fsstress](https://www2.cs.duke.edu/ari/fstress/).

**Comment by OmSaran** [comment]
#16 - Here is an attempt to make changes to support the test suite

**Comment by vijay03** [comment]
Solved by #16. Thanks @om-saran!
