### ISSUE TITLE
About supporting fio

### ISSUE THREAD

**Issue by leftgeek** [utsaslab/SplitFS#45]
When I run fio on splitfs, it always fails in _hub_FOPEN("/proc/self/status") and gets
`NVP_ASSERT(_hub_managed_fileops != NULL) failed!`

It seems that the libnvp.so is not loaded, but filebench and other shell commands such as "ls, df" can be intercepted successfully by splitfs.

I also noticed that the filebench code under splitfs is almost unmodified.
How should I start to modify fio to run on splitfs?

**Comment by rohankadekodi** [comment]
I have added FIO support to SplitFS. You can pull the latest code from the master branch. It has the details in README about how to run FIO.

**Comment by kongnull** [comment]
Thanks, it worked.
Several fio files are missing:
lib/output_buffer.h
lib/output_buffer.c
blktrace.h
blktrace.c
blktrace_api.h
