### ISSUE TITLE
Missing fsync after creation of operation log file

### ISSUE THREAD

**Issue by OmSaran** [utsaslab/SplitFS#59]
[After creating the operation log file](https://github.com/utsaslab/SplitFS/blob/46f337364c5ac222429be758b611f42ad127484f/splitfs/log.c#L201), we do not seem to be doing an `fsync`. 

This does not guarantee the creation of `operation.log` and could end up in missing metadata information (about the presence of the op log file) and hence loss of any op logs entries.

This was observed when a crash was simulated after creation of a file `/mnt/pmem_emul/foo` but upon restart, the `operation.log` file was missing. Adding an `fsync` resolved the presence of operation.log issue.

PS: The same is true for `append.log`

**Comment by OmSaran** [comment]
Here's an attempted fix: #61

**Comment by rohankadekodi** [comment]
Thanks for finding the bug and the fix! It has been merged to master.
