### ISSUE TITLE
ext4/kernel changes commits

### ISSUE THREAD

**Issue by riteshharjani** [utsaslab/SplitFS#7]
Hello SplitFS Team, 

Are there direct commits/patches which we could check to see to understand what are the ext4/kernel side of the changes required for SplitFS? Could you point to those commits/patches, instead of the whole kernel pls?

**Comment by vijay03** [comment]
Yup, the changes are pretty localized (small changes to 3 or 4 files). @rohankadekodi can you point out the changes, and actually create a patch for the kernel version we tested SplitFS on? Then folks can then directly apply those patches to their kernel.

**Comment by riteshharjani** [comment]
>> can you point out the changes, and actually create a patch for the kernel version we tested SplitFS >> on?Then folks can then directly apply those patches to their kernel.
[rh] -Yes, that would be great!!

**Comment by rohankadekodi** [comment]
I have added a patch for the Linux 4.13 kernel (on which we tested SplitFS) to the repository. The link is [here](https://github.com/utsaslab/SplitFS/blob/master/kernel/splitfs_kernel.patch)

I will close this issue now, but please contact me if you face issues.
